rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
before_install:
  - gem update --system
  - sudo apt-get install dictionaries-common wamerican libglib2.0-dev libatk1.0-dev libcairo-dev libsqlite3-dev libpango1.0-dev libgtk2.0-dev
script: "bundle exec cucumber ./features"
branches:
  only:
    - master
